import { Metadata } from "next";
import { Globe, Brain, Newspaper, BarChart3 } from "lucide-react";

export const metadata: Metadata = {
  title: "About WW3 Predictor — AI-Powered Geopolitical Risk Analysis",
  description:
    "Learn how WW3 Predictor uses Claude AI and real-time news to assess global conflict risk. Our methodology, data sources, and disclaimer.",
};

export default function AboutPage() {
  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
      <div className="mb-10">
        <h1 className="text-3xl font-bold text-white mb-3">About WW3 Predictor</h1>
        <p className="text-gray-400 text-lg leading-relaxed">
          WW3 Predictor is an independent, AI-powered geopolitical risk monitor
          that tracks global conflict indicators in real time.
        </p>
      </div>

      {/* What we do */}
      <section className="mb-10">
        <h2 className="text-xl font-semibold text-white mb-4">What We Do</h2>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          {[
            {
              icon: <Newspaper className="w-6 h-6 text-blue-400" />,
              title: "News Aggregation",
              desc: "We pull the top conflict-related headlines from Reuters, BBC, AP, and 80+ major outlets via NewsAPI every 6 hours.",
            },
            {
              icon: <Brain className="w-6 h-6 text-purple-400" />,
              title: "AI Analysis",
              desc: "Claude AI (claude-sonnet-4-6 by Anthropic) analyzes these headlines and assigns a geopolitical risk score from 0–100.",
            },
            {
              icon: <BarChart3 className="w-6 h-6 text-red-400" />,
              title: "Risk Scoring",
              desc: "The score reflects current military escalations, diplomatic failures, nuclear threats, and alliance shifts.",
            },
            {
              icon: <Globe className="w-6 h-6 text-green-400" />,
              title: "Public Dashboard",
              desc: "We display the score publicly so anyone can track global conflict risk without needing a geopolitics background.",
            },
          ].map((item) => (
            <div
              key={item.title}
              className="bg-gray-900 border border-gray-800 rounded-xl p-5"
            >
              <div className="mb-3">{item.icon}</div>
              <h3 className="text-white font-semibold mb-1.5">{item.title}</h3>
              <p className="text-gray-400 text-sm leading-relaxed">{item.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Methodology */}
      <section className="mb-10">
        <h2 className="text-xl font-semibold text-white mb-4">Methodology</h2>
        <div className="bg-gray-900/60 border border-gray-800 rounded-xl p-6 space-y-3 text-sm text-gray-300 leading-relaxed">
          <p>
            <strong className="text-white">1. Data Collection:</strong> Every 6
            hours, our system fetches up to 20 conflict-relevant headlines using
            keywords like war, military, nuclear, NATO, missile, Russia, China,
            North Korea, Iran, Israel, Gaza, and Ukraine.
          </p>
          <p>
            <strong className="text-white">2. AI Prompt:</strong> These headlines
            are passed to Claude AI with a structured prompt asking it to assess
            WW3 probability on a 0–100 scale, identify key contributing factors,
            and provide a reasoning summary.
          </p>
          <p>
            <strong className="text-white">3. Score Guidelines:</strong> 0–20 =
            Low (normal tensions), 21–40 = Elevated, 41–60 = Moderate, 61–80 =
            High Alert, 81–100 = Critical.
          </p>
          <p>
            <strong className="text-white">4. Storage:</strong> Scores are stored
            in a Supabase database and served via edge-cached API routes.
          </p>
        </div>
      </section>

      {/* Disclaimer */}
      <section className="mb-10">
        <h2 className="text-xl font-semibold text-white mb-4">Disclaimer</h2>
        <div className="bg-yellow-950/30 border border-yellow-900/40 rounded-xl p-6 text-sm text-yellow-200/80 leading-relaxed">
          <p>
            WW3 Predictor is an <strong>informational tool only</strong>. The
            scores and analysis provided are generated by an AI model and do NOT
            constitute intelligence assessments, political advice, financial
            advice, or any form of prediction guaranteed to be accurate.
          </p>
          <p className="mt-3">
            The probability meter reflects AI interpretation of publicly available
            news, which may be incomplete, biased, or inaccurate. We are not
            affiliated with any government, military organization, or intelligence
            agency.
          </p>
        </div>
      </section>

      {/* Tech stack */}
      <section>
        <h2 className="text-xl font-semibold text-white mb-4">Built With</h2>
        <div className="flex flex-wrap gap-2">
          {[
            "Next.js 14",
            "TypeScript",
            "Tailwind CSS",
            "Claude AI (Anthropic)",
            "NewsAPI",
            "Supabase",
            "Vercel",
          ].map((tech) => (
            <span
              key={tech}
              className="bg-gray-800 border border-gray-700 text-gray-300 text-sm px-3 py-1 rounded-full"
            >
              {tech}
            </span>
          ))}
        </div>
      </section>
    </div>
  );
}
